# Generated by Django 3.1.7 on 2021-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=30)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
